// Portafolio: SOLO piezas reales producidas por InnovArtis.
// Cada métrica lleva la fecha en que se leyó en la red del cliente (nunca inventar).
// Vetados en la web: Tokilla, Surty, Óptica, Aquabec.
// type: "img" | "video" · metric opcional: { value, label, date }

export const RUBROS = ["Todos", "Belleza", "Limpieza", "Industria", "Alimentos", "Mascotas", "Gastronomía", "Educación", "Salud", "Servicios"];

// href: enlace a la publicación real (la captura muestra los números tal como estaban ese día).
export const PORTFOLIO = [
  {
    src: "/portafolio/inyecpro/reel-vasos-1mil.webp",
    type: "img",
    client: "InyecPro · fábrica de plásticos",
    rubro: "Industria",
    piece: "Reel · captura de Facebook, 5-oct-2026",
    metric: { value: "1 mil", label: "me gusta · 99 comentarios · 36 compartidos" },
    href: "https://www.facebook.com/reel/1374759481081194",
  },
  {
    src: "/portafolio/ads/inyecpro-may-oct.webp",
    type: "img",
    client: "InyecPro · fábrica de plásticos",
    rubro: "Industria",
    piece: "Ads Manager · 5-may al 4-oct-2026",
    metric: { value: 1729, label: "conversaciones por WhatsApp a $0,57 c/u" },
  },
  {
    src: "/portafolio/damavid/reel-62mil.webp",
    type: "img",
    client: "Damavid Aqua · agua purificada",
    rubro: "Alimentos",
    piece: "Reel · captura de Facebook, 5-oct-2026",
    metric: { value: "62 mil", label: "reproducciones · 576 me gusta · 33 compartidos" },
    href: "https://www.facebook.com/reel/4297411207210341",
  },
  {
    src: "/portafolio/ads/damavid-jun-oct.webp",
    type: "img",
    client: "Damavid Aqua · agua purificada",
    rubro: "Alimentos",
    piece: "Ads Manager · 1-jun al 4-oct-2026",
    metric: { value: 329, label: "conversaciones por WhatsApp a $0,95 c/u" },
  },
  {
    src: "/portafolio/pachy/post-1.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Post · limpieza industrial",
    metric: { value: 3548, label: "conversaciones por WhatsApp en 12 meses, desde $0,44 c/u" },
  },
  {
    src: "/portafolio/ads/pachy-2026.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Ads Manager · 1-ene al 4-oct-2026",
    metric: { value: 2508, label: "conversaciones por WhatsApp a $0,68 c/u" },
  },
  {
    src: "/portafolio/pachy/post-2.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Post · antes y después",
  },
  {
    src: "/portafolio/pachy/carrusel-servicios.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Carrusel · catálogo de servicios",
  },
  {
    src: "/portafolio/pachy/antes-despues.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Antes y después",
  },
  {
    src: "/portafolio/pachy/clientes-felices.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Carrusel · clientes felices",
  },
  {
    src: "/portafolio/remy/arte-extensiones-cabello-transforma.jpg",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Arte para Instagram",
    metric: { value: 9512, label: "conversaciones por WhatsApp en 12 meses, desde $0,32 c/u" },
  },
  {
    src: "/portafolio/remy/carrusel-3razones-portada.jpg",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Carrusel · portada",
    metric: { value: 4803, label: "conversaciones en Guayaquil a $0,32 c/u" },
  },
  {
    src: "/portafolio/remy/carrusel-3razones-01-mas-largo.jpg",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Carrusel · lámina 1",
  },
  {
    src: "/portafolio/remy/carrusel-3razones-02-mas-volumen.jpg",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Carrusel · lámina 2",
  },
  {
    src: "/portafolio/remy/carrusel-3razones-03-cabello-sano.jpg",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Carrusel · lámina 3",
  },
  {
    src: "/portafolio/remy/cliente-antes-extensiones.jpg",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Antes",
  },
  {
    src: "/portafolio/remy/cliente-despues-extensiones.jpg",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Después",
  },
  {
    src: "/portafolio/remy/arte-pestanas-remy-sur.jpg",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Arte · local del sur",
  },
  {
    src: "/portafolio/ads/metallum-30d.webp",
    type: "img",
    client: "Metallum · pérgolas y estructuras",
    rubro: "Industria",
    piece: "Ads Manager · 5-sep al 4-oct-2026",
    metric: { value: 239, label: "clientes potenciales (formulario) a $0,41 c/u" },
  },
  {
    src: "/portafolio/controlfrio/servicios.webp",
    type: "img",
    client: "Controlfrío · climatización industrial",
    rubro: "Industria",
    piece: "Post · servicios",
  },
  {
    src: "/portafolio/controlfrio/lluvias.webp",
    type: "img",
    client: "Controlfrío · climatización industrial",
    rubro: "Industria",
    piece: "Post · temporada de lluvias",
  },
  {
    src: "/portafolio/sertec/1.webp",
    type: "img",
    client: "SERTEC Generación · generadores",
    rubro: "Industria",
    piece: "Post · soporte técnico",
  },
  {
    src: "/portafolio/sertec/2.webp",
    type: "img",
    client: "SERTEC Generación · generadores",
    rubro: "Industria",
    piece: "Post · stock de repuestos",
  },
  {
    src: "/portafolio/sertec/3.webp",
    type: "img",
    client: "SERTEC Generación · generadores",
    rubro: "Industria",
    piece: "Post · repuestos",
  },
  {
    src: "/portafolio/enquality/san-valentin.webp",
    type: "img",
    client: "Enquality · academia de inglés",
    rubro: "Educación",
    piece: "Post · promo San Valentín",
  },
  {
    src: "/portafolio/enquality/marzo-2.webp",
    type: "img",
    client: "Enquality · academia de inglés",
    rubro: "Educación",
    piece: "Post · promo de marzo",
  },
  {
    src: "/portafolio/enquality/carrusel-1.webp",
    type: "img",
    client: "Enquality · academia de inglés",
    rubro: "Educación",
    piece: "Carrusel · portada",
  },
  {
    src: "/portafolio/enquality/carrusel-2.webp",
    type: "img",
    client: "Enquality · academia de inglés",
    rubro: "Educación",
    piece: "Carrusel · lámina 2",
  },
  {
    src: "/portafolio/enquality/carrusel-3.webp",
    type: "img",
    client: "Enquality · academia de inglés",
    rubro: "Educación",
    piece: "Carrusel · lámina 3",
  },
  {
    src: "/portafolio/ads/kya-ago.webp",
    type: "img",
    client: "KYA Ecuador · capacitación ISO",
    rubro: "Educación",
    piece: "Ads Manager · 25-jul al 30-ago-2026",
    metric: { value: 347, label: "clientes potenciales (formulario) a $0,55 c/u" },
  },
  {
    src: "/portafolio/metallum/d-post-propuesta.webp",
    type: "img",
    client: "Metallum · pérgolas y estructuras",
    rubro: "Industria",
    piece: "Post · áreas exteriores",
  },
  {
    src: "/portafolio/metallum/d-carrusel-1.webp",
    type: "img",
    client: "Metallum · pérgolas y estructuras",
    rubro: "Industria",
    piece: "Carrusel · aluminio maderado",
  },
  {
    src: "/portafolio/metallum/d-carrusel-2.webp",
    type: "img",
    client: "Metallum · pérgolas y estructuras",
    rubro: "Industria",
    piece: "Carrusel · lámina 2",
  },
  {
    src: "/portafolio/metallum/d-carrusel-3.webp",
    type: "img",
    client: "Metallum · pérgolas y estructuras",
    rubro: "Industria",
    piece: "Carrusel · lámina 3",
  },
  {
    src: "/portafolio/metallum/d-portada-fb.webp",
    type: "img",
    client: "Metallum · pérgolas y estructuras",
    rubro: "Industria",
    piece: "Portada de Facebook",
  },
  {
    src: "/portafolio/medcentral/d-post-1.webp",
    type: "img",
    client: "MedCentral · centro médico",
    rubro: "Salud",
    piece: "Post · señales de alerta",
  },
  {
    src: "/portafolio/medcentral/d-carrusel-1.webp",
    type: "img",
    client: "MedCentral · centro médico",
    rubro: "Salud",
    piece: "Carrusel · portada",
  },
  {
    src: "/portafolio/medcentral/d-carrusel-2.webp",
    type: "img",
    client: "MedCentral · centro médico",
    rubro: "Salud",
    piece: "Carrusel · lámina 2",
  },
  {
    src: "/portafolio/medcentral/d-carrusel-3.webp",
    type: "img",
    client: "MedCentral · centro médico",
    rubro: "Salud",
    piece: "Carrusel · lámina 3",
  },
  {
    src: "/portafolio/serenite/d-antes-despues.webp",
    type: "img",
    client: "Serenité · uñas y belleza",
    rubro: "Belleza",
    piece: "Antes y después",
  },
  {
    src: "/portafolio/vet-metropolis/d-portada-fb.webp",
    type: "img",
    client: "Clínica Veterinaria Metrópolis",
    rubro: "Mascotas",
    piece: "Portada de Facebook",
  },
  {
    src: "/portafolio/sertec/d-mateo-carrusel-1.webp",
    type: "img",
    client: "SERTEC Generación · generadores",
    rubro: "Industria",
    piece: "Carrusel · mantenimiento de generadores",
  },
  {
    src: "/portafolio/sertec/d-mateo-carrusel-2.webp",
    type: "img",
    client: "SERTEC Generación · generadores",
    rubro: "Industria",
    piece: "Carrusel · lámina 2",
  },
  {
    src: "/portafolio/sertec/d-mateo-carrusel-3.webp",
    type: "img",
    client: "SERTEC Generación · generadores",
    rubro: "Industria",
    piece: "Carrusel · lámina 3",
  },
  {
    src: "/portafolio/sertec/d-post-12mar.webp",
    type: "img",
    client: "SERTEC Generación · generadores",
    rubro: "Industria",
    piece: "Post · traslado y puesta en marcha",
  },
  {
    src: "/portafolio/sertec/d-carrusel-repuestos-1.webp",
    type: "img",
    client: "SERTEC Generación · generadores",
    rubro: "Industria",
    piece: "Carrusel · repuestos",
  },
  {
    src: "/portafolio/sertec/d-carrusel-servicios-2.webp",
    type: "img",
    client: "SERTEC Generación · generadores",
    rubro: "Industria",
    piece: "Carrusel · servicios",
  },
  {
    src: "/portafolio/controlfrio/d-post-31mar-1.webp",
    type: "img",
    client: "Controlfrío · climatización industrial",
    rubro: "Industria",
    piece: "Post · ¿tu aire no rinde?",
  },
  {
    src: "/portafolio/controlfrio/d-post-31mar-2.webp",
    type: "img",
    client: "Controlfrío · climatización industrial",
    rubro: "Industria",
    piece: "Post · no solo instalamos",
  },
  {
    src: "/portafolio/pachy/d-mateo-post-1.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Post · limpieza profunda",
  },
  {
    src: "/portafolio/pachy/d-mateo-post-2.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Post · casas de campo y fincas",
  },
  {
    src: "/portafolio/pachy/d-mateo-carrusel-1.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Carrusel · la primera impresión",
  },
  {
    src: "/portafolio/pachy/d-mateo-carrusel-2.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Carrusel · exteriores",
  },
  {
    src: "/portafolio/pachy/d-carrusel-feb-1.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Carrusel · razones para elegirnos",
  },
  {
    src: "/portafolio/pachy/d-carrusel-feb-3.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Carrusel · agenda tu servicio",
  },
  {
    src: "/portafolio/remy/d-arte-aura.webp",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Post · nuevo estilo Aura",
  },
  {
    src: "/portafolio/remy/d-pestanas-carrusel-1.webp",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Carrusel · pestañas",
  },
  {
    src: "/portafolio/remy/d-san-valentin.webp",
    type: "img",
    client: "Cabello Remy EC",
    rubro: "Belleza",
    piece: "Post · San Valentín",
  },
  {
    src: "/portafolio/contaservis/m-j4.webp",
    type: "img",
    client: "Contaservis · servicios contables",
    rubro: "Servicios",
    piece: "Anuncio · florícolas y exportadores",
  },
  {
    src: "/portafolio/contaservis/m-j8.webp",
    type: "img",
    client: "Contaservis · servicios contables",
    rubro: "Servicios",
    piece: "Anuncio · servicios de contabilidad",
  },
  {
    src: "/portafolio/contaservis/m-j9.webp",
    type: "img",
    client: "Contaservis · servicios contables",
    rubro: "Servicios",
    piece: "Anuncio · servicios contables",
  },
  {
    src: "/portafolio/solugraf/m-s1.webp",
    type: "img",
    client: "Solugraf · imprenta y empaques",
    rubro: "Industria",
    piece: "Anuncio · empaques para comida rápida",
  },
  {
    src: "/portafolio/solugraf/m-s9.webp",
    type: "img",
    client: "Solugraf · imprenta y empaques",
    rubro: "Industria",
    piece: "Anuncio · empaques delivery",
  },
  {
    src: "/portafolio/solugraf/m-s3.webp",
    type: "img",
    client: "Solugraf · imprenta y empaques",
    rubro: "Industria",
    piece: "Anuncio · Black Friday carpetas",
  },
  {
    src: "/portafolio/solugraf/m-s10.webp",
    type: "img",
    client: "Solugraf · imprenta y empaques",
    rubro: "Industria",
    piece: "Anuncio · promoción tricolor",
  },
  {
    src: "/portafolio/hampi-andina/m-h3.webp",
    type: "img",
    client: "Hampi Andina · medicina ancestral",
    rubro: "Salud",
    piece: "Anuncio · webinar gratuito",
  },
  {
    src: "/portafolio/hampi-andina/m-h7.webp",
    type: "img",
    client: "Hampi Andina · medicina ancestral",
    rubro: "Salud",
    piece: "Anuncio · taller de abundancia",
  },
  {
    src: "/portafolio/hampi-andina/m-h1.webp",
    type: "img",
    client: "Hampi Andina · medicina ancestral",
    rubro: "Salud",
    piece: "Anuncio · webinar medicina andina",
  },
  {
    src: "/portafolio/inyecto-bien/m-an9.webp",
    type: "img",
    client: "Inyecto Bien · cursos de inyectología",
    rubro: "Educación",
    piece: "Anuncio · curso de toxina botulínica",
  },
  {
    src: "/portafolio/inyecto-bien/m-an1.webp",
    type: "img",
    client: "Inyecto Bien · cursos de inyectología",
    rubro: "Educación",
    piece: "Anuncio · curso de plasma rico en plaquetas",
  },
  {
    src: "/portafolio/inyecto-bien/m-an10.webp",
    type: "img",
    client: "Inyecto Bien · cursos de inyectología",
    rubro: "Educación",
    piece: "Anuncio · curso de inyectología",
  },
  {
    src: "/portafolio/las-humitas/m-g8.webp",
    type: "img",
    client: "Las Humitas de la Loma",
    rubro: "Alimentos",
    piece: "Anuncio · 100 % choclo",
  },
  {
    src: "/portafolio/las-humitas/m-g7.webp",
    type: "img",
    client: "Las Humitas de la Loma",
    rubro: "Alimentos",
    piece: "Anuncio · 4 x $1",
  },
  {
    src: "/portafolio/jorge-murillo/m-jm1.webp",
    type: "img",
    client: "Jorge Murillo · seguros",
    rubro: "Servicios",
    piece: "Anuncio · reembolso en línea",
  },
  {
    src: "/portafolio/abbysal/m-a3.webp",
    type: "img",
    client: "Abbysal Tentacle Cravings",
    rubro: "Gastronomía",
    piece: "Anuncio · gran inauguración",
  },
  {
    src: "/portafolio/abbysal/m-a2.webp",
    type: "img",
    client: "Abbysal Tentacle Cravings",
    rubro: "Gastronomía",
    piece: "Anuncio · monstruosamente delicioso",
  },
  {
    src: "/portafolio/inyecpro/m-i5.webp",
    type: "img",
    client: "InyecPro · fábrica de plásticos",
    rubro: "Industria",
    piece: "Anuncio · ¿tu proveedor está fallando?",
  },
  {
    src: "/portafolio/inyecpro/m-i4.webp",
    type: "img",
    client: "InyecPro · fábrica de plásticos",
    rubro: "Industria",
    piece: "Anuncio · evaluación técnica gratuita",
  },
  {
    src: "/portafolio/inyecpro/m-i7.webp",
    type: "img",
    client: "InyecPro · fábrica de plásticos",
    rubro: "Industria",
    piece: "Anuncio · qué obtienes",
  },
  {
    src: "/portafolio/inyecpro/m-i9.webp",
    type: "img",
    client: "InyecPro · fábrica de plásticos",
    rubro: "Industria",
    piece: "Anuncio · asegura tu suministro",
  },
  {
    src: "/portafolio/damavid/m-d4.webp",
    type: "img",
    client: "Damavid Aqua · agua purificada",
    rubro: "Alimentos",
    piece: "Anuncio · dispensadores para tu hogar",
  },
  {
    src: "/portafolio/metallum/m-m1.webp",
    type: "img",
    client: "Metallum · pérgolas y estructuras",
    rubro: "Industria",
    piece: "Anuncio · pérgolas",
  },
  {
    src: "/portafolio/metallum/m-m2.webp",
    type: "img",
    client: "Metallum · pérgolas y estructuras",
    rubro: "Industria",
    piece: "Anuncio · construcción",
  },
  {
    src: "/portafolio/pachy/m-p6.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Anuncio · trabajo en altura",
  },
  {
    src: "/portafolio/pachy/m-p9.webp",
    type: "img",
    client: "Pachy Limpieza Profesional",
    rubro: "Limpieza",
    piece: "Anuncio · limpieza de exteriores",
  },
  {
    src: "/portafolio/controlfrio/m-mg3.webp",
    type: "img",
    client: "Controlfrío · climatización industrial",
    rubro: "Industria",
    piece: "Anuncio · mantenimiento de aire",
  },
  {
    src: "/portafolio/kya/m-k1.webp",
    type: "img",
    client: "KYA Ecuador · capacitación ISO",
    rubro: "Educación",
    piece: "Anuncio · curso gratis ISO",
  },
  {
    src: "/img/caso-metropolis.webp",
    type: "img",
    client: "Clínica Veterinaria Metrópolis",
    rubro: "Mascotas",
    piece: "Redes desde cero",
    metric: { value: 26, label: "likes · 2 comentarios respondidos" },
  },
  {
    src: "/img/caso-idefix.webp",
    type: "img",
    client: "Idefix · Plastics Ide",
    rubro: "Industria",
    piece: "Marca y reels de producto",
    metric: { value: 204, label: "likes en un reel de producto" },
  },
  {
    src: "/img/caso-abbysal.webp",
    type: "img",
    client: "Abbysal Tentacle Cravings",
    rubro: "Gastronomía",
    piece: "Cobertura de lanzamiento",
    metric: { value: 74, label: "likes en el reel de lanzamiento" },
  },
];
